spring:
  application:
    name: tracker
  server:
    port: 8080
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

kotak:
  auth:
    token: ${KOTAK_TOKEN}

spring:
  application:
    name: tracker
  datasource:
    url: jdbc:postgresql://db.tbrwwkjskjzjsfismcyw.supabase.co:5432/postgres
    username: postgres
    password: Yogendra@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

kotak:
  auth:
    token: 2250619a-01a9-46a2-9231-1e366c24a9c3

firebase:
  config:
    path: static/ftle-firebase-adminsdk.json

#frontend:
#  url: ${FRONTEND_URL}

frontend:
  url: http://localhost:5173/